# Generated by Django 3.2 on 2023-04-17 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date publised')),
            ],
        ),
        migrations.CreateModel(
            name='respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion_texto', models.CharField(max_length=200)),
                ('valor', models.IntegerField(default=1)),
                ('pregunta1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.entrega')),
            ],
        ),
    ]
